services:
  - type: web
    name: dockviz-backend
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run start
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
