services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      pyenv install 3.12.2
      pyenv global 3.12.2
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: poetry run start
