services:
  - type: web
    name: docviz-backend
    env: python
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi
    startCommand: poetry run start
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
